# Generated by Django 5.0.3 on 2024-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='my_image', verbose_name='photo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
        ),
    ]
